version: 0.1

phases:
  pre_build:
    commands:
      - echo is login needed with service role in codebuild setup?      

  build:
    commands:
      - docker build -t phoenix/phoenix-ui .
      - docker tag phoenix/phoenix-ui:latest 887583529513.dkr.ecr.us-east-1.amazonaws.com/phoenix/phoenix-ui:latest

  post_build:
    commands:
      - echo Pushing the Docker image…
      # - docker push 887583529513.dkr.ecr.us-east-1.amazonaws.com/phoenix/phoenix-ui:latest

artifacts:
  files:
    - '**/*'

name: phoenix-ui
